version: '3'

services:
  minio9901:
    image: minio/minio:RELEASE.2017-03-16T21-50-32Z
    volumes:
      - minio9901-data:/export
    ports:
      - "9901:9000"
    networks:
      - minio_distributed_99
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio9901/export http://minio9902/export http://minio9903/export http://minio9904/export

  minio9902:
    image: minio/minio:RELEASE.2017-03-16T21-50-32Z
    volumes:
      - minio9902-data:/export
    ports:
      - "9902:9000"
    networks:
      - minio_distributed_99
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio9901/export http://minio9902/export http://minio9903/export http://minio9904/export

  minio9903:
    image: minio/minio:RELEASE.2017-03-16T21-50-32Z
    volumes:
      - minio9903-data:/export
    ports:
      - "9903:9000"
    networks:
      - minio_distributed_99
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio9901/export http://minio9902/export http://minio9903/export http://minio9904/export

  minio9904:
    image: minio/minio:RELEASE.2017-03-16T21-50-32Z
    volumes:
      - minio9904-data:/export
    ports:
      - "9904:9000"
    networks:
      - minio_distributed_99
    environment:
      MINIO_ACCESS_KEY: AKIAIOSFODNN7EXAMPLE
      MINIO_SECRET_KEY: wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY
    deploy:
      restart_policy:
        delay: 10s
        max_attempts: 10
        window: 60s
    command: server http://minio9901/export http://minio9902/export http://minio9903/export http://minio9904/export

volumes:
  minio9901-data:

  minio9902-data:

  minio9903-data:

  minio9904-data:

networks:
  minio_distributed_99:
    driver: overlay
